spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&userLegacyDatetimeCode=false
    # username: root
    # password: root
    url: postgres://cucfcjkzoismcy:6c6c6843e56ef9b098217a664e556a602b57c94b834b8df8227f04c7d6358fd5@ec2-34-198-31-223.compute-1.amazonaws.com:5432/dcv2d5dlie6jsv
    username: cucfcjkzoismcy
    password: 6c6c6843e56ef9b098217a664e556a602b57c94b834b8df8227f04c7d6358fd5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

jwt:
  expiration:
    time: 90000

# Documentacion:
# http://localhost:8080/v3/api-docs/
# http://localhost:8080/swagger-ui.html